source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '9.0'

target 'HeartRateExporter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeartRateExporter
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'AWSAutoScaling'
  pod 'AWSCloudWatch'
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSDynamoDB'
  pod 'AWSEC2'
  pod 'AWSElasticLoadBalancing'
  pod 'AWSIoT'
  pod 'AWSKinesis'
  pod 'AWSLambda'
  pod 'AWSLex'
  pod 'AWSMachineLearning'
  pod 'AWSMobileAnalytics'
  pod 'AWSPinpoint'
  pod 'AWSPolly'
  pod 'AWSRekognition'
  pod 'AWSS3'
  pod 'AWSSES'
  pod 'AWSSimpleDB'
  pod 'AWSSNS'
 
  pod 'AWSSQS'
  target 'HeartRateExporterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
